version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./public:/app/public
    environment:
      - MODE=${MODE:-wasm}
      - PORT=3000
    restart: unless-stopped